// apps/projects-solid/src/components/editable-date.tsx
import type { JSX } from 'solid-js';
import EditableText, { type EditableTextProps } from './editable-text';

export default (
  props: Omit<EditableTextProps, 'on:change'> & {
    'on:change'?: JSX.ChangeEventHandler<HTMLInputElement, Event>;
  },
) => {
  const getValue = props.value;

  props.value = () => {
    const value = getValue();
    return value ? new Date(value).toISOString() : '';
  };

  if (props['on:change']) {
    const original = props['on:change'];
    props['on:change'] = (e) => !isNaN(Date.parse(e.target.value)) && original(e);
  }

  return <EditableText {...props} />;
};

// src/lib/client/components/editable/editable-date.svelte
<script lang="ts">
  import type { EditableProps } from './editable-props';
  import EditableText from './editable-text.svelte';

  let {
    editing = $bindable(false),
    value = $bindable(''),
    onedit,
  }: Pick<EditableProps, 'editing' | 'value' | 'onedit'> = $props();
</script>

<EditableText
  bind:editing
  bind:value
  placeholder="YYYY-MM-DD HH:mm:ss"
  render={(v) => (v ? new Date(v).toLocaleString() : '')}
  transform={(v) => (v ? new Date(v).toISOString() : '')}
  validate={(v) => (v ? !isNaN(Date.parse(v)) : false)}
  {onedit}
/>
