// src/routes/+page.svelte
<script lang="ts">
  import EditableDate from '$lib/client/components/editable/editable-date.svelte';
  import EditableText from '$lib/client/components/editable/editable-text.svelte';
  import { deleteEntity } from '$lib/client/data/entity';
  import { Entity } from '$lib/client/data/entity.svelte';
  import { root, rootCID } from '$lib/client/data/root.svelte';
  import EntityDependencies from './entity-dependencies.svelte';

  let addingTask = $state(false);
  let hideBlocked = $state(true);
  let hideFuture = $state(true);

  let blocked = $derived(root.childrenEnt.filter((ent) => !!ent.dependencies.length));

  async function addTask(name: string) {
    if (name) {
      const entity = new Entity();
      entity.name = name;
      entity.parent = rootCID;
      const cid = await entity.save();
      if (cid) {
        root.children.unshift(cid);
        root.save();
      }
    }
    addingTask = false;
  }
</script>

<label class="m-2">
  <input type="checkbox" bind:checked={hideFuture} />
  Hide future tasks
</label>

<label class="m-2">
  <input type="checkbox" bind:checked={hideBlocked} />
  Hide blocked tasks
</label>

<label class="m-2">
  <input type="checkbox" bind:checked={hideCompleted} />
  Hide completed tasks
</label>

<table class="w-full">
  <thead>
    <tr>
      <th>Task</th>
      <th>Start</th>
      <th>End</th>
      <th>Dependencies</th>
      <th>Created</th>
      <th>Updated</th>
      <th class="text-right">
        <button disabled={!!addingTask} onclick={() => (addingTask = true)}>Add task</button>
      </th>
    </tr>
  </thead>
  <tbody>
    {#if addingTask}
      <tr>
        <td colspan="7">
          <EditableText
            editing={true}
            placeholder="New task"
            transform={(v) => v.trim()}
            onedit={addTask}
          />
        </td>
      </tr>
    {/if}
    {#each root.childrenEnt as ent, i}
      {#if (!hideFuture || !ent.start || ent.start.getTime() <= Date.now()) && (!hideBlocked || !blocked.includes(ent))}
        <tr>
          <td>
            <EditableText
              value={ent.name}
              transform={(v) => v.trim()}
              onedit={async (newName) => {
                if (typeof newName === 'string' && newName !== ent.name && root.children) {
                  ent.name = newName;
                  root.children[i] = await ent.save();
                  root.save();
                }
              }}
            />
          </td>
          <td>
            <EditableDate
              value={ent.start?.toISOString()}
              onedit={async (start) => {
                const newDate = new Date(start);
                if (newDate.getTime() !== ent.start?.getTime() && root.children) {
                  ent.start = newDate;
                  root.children[i] = await ent.save();
                  root.save();
                }
              }}
            />
            {#if ent.start}
              <button
                onclick={async () => {
                  if (root.children) {
                    ent.start = undefined;
                    root.children[i] = await ent.save();
                    root.save();
                  }
                }}>x</button
              >
            {/if}
          </td>
          <td>
            <EditableDate
              value={ent.end?.toISOString()}
              onedit={async (end) => {
                const newDate = new Date(end);
                if (newDate.getTime() !== ent.start?.getTime() && root.children) {
                  ent.end = newDate;
                  root.children[i] = await ent.save();
                  root.save();
                }
              }}
            />
            {#if ent.end}
              <button
                onclick={async () => {
                  if (root.children) {
                    ent.end = undefined;
                    root.children[i] = await ent.save();
                    root.save();
                  }
                }}>x</button
              >
            {/if}
          </td>
          <td>
            <EntityDependencies {ent} />
          </td>
          <td>
            {ent.created?.toLocaleDateString()}
          </td>
          <td>
            {ent.updated?.toLocaleDateString()}
          </td>
          <td class="text-right">
            <button onclick={() => ent.cid && deleteEntity(ent.cid, i)}>Delete</button>
          </td>
        </tr>
      {/if}
    {/each}
  </tbody>
</table>

// apps/projects/src/routes/index.tsx
import { Title } from '@solidjs/meta';
// prettier-ignore
import { type Accessor, createMemo, createSignal, For, type JSX, type ParentProps, type Setter, Show, type Signal } from 'solid-js';
import EditableDate from '~/components/editable-date';
import EditableText from '~/components/editable-text';
// prettier-ignore
import { entities, entityDependencies, objectToEntity, setEntities, setEntityDependencies } from '~/lib/entities';

const FilterCheckbox = ({
  children,
  get,
  set,
}: ParentProps<{ get: Accessor<boolean>; set: Setter<boolean> }>): JSX.Element => (
  <label class="m-2">
    <input type="checkbox" checked={get()} on:change={(e) => set(e.target.checked)} />
    {children}
  </label>
);

export default () => {
  const [addingTask, setAddingTask] = createSignal(false);

  const [hideBlocked, setHideBlocked] = createSignal(true);
  const [hideCompleted, setHideCompleted] = createSignal(true);
  const [hideFuture, setHideFuture] = createSignal(true);

  let newTaskInput!: HTMLInputElement;

  return (
    <main>
      <Title>Home | Luna Projects</Title>

      <FilterCheckbox get={hideBlocked} set={setHideBlocked}>
        Hide blocked tasks
      </FilterCheckbox>

      <FilterCheckbox get={hideCompleted} set={setHideCompleted}>
        Hide completed tasks
      </FilterCheckbox>

      <FilterCheckbox get={hideFuture} set={setHideFuture}>
        Hide future tasks
      </FilterCheckbox>

      <table class="w-full">
        <thead>
          <tr>
            <th>Task</th>
            <th>Completed</th>
            <th>Start</th>
            <th>End</th>
            <th>Dependencies</th>
            <th>Created</th>
            <th>Updated</th>
            <th class="text-right">
              <button
                disabled={addingTask()}
                on:click={() => {
                  setAddingTask(true);
                  newTaskInput.focus();
                }}
              >
                Add task
              </button>
            </th>
          </tr>
        </thead>
        <tbody>
          <Show when={addingTask()}>
            <tr>
              <td colspan="8">
                <input
                  ref={newTaskInput}
                  class="w-full"
                  placeholder="New task"
                  on:blur={(e) => {
                    const name = e.currentTarget.value.trim();
                    if (name) {
                      setEntities((entities) => [objectToEntity({ name }), ...entities]);
                    }
                    setAddingTask(false);
                  }}
                  on:keydown={(e) =>
                    (e.key === 'Escape' || e.key === 'Enter') && e.currentTarget.blur()
                  }
                />
              </td>
            </tr>
          </Show>
          <For each={entities()}>
            {(entity, i) => {
              const [name, setName] = entity.name;
              const [completed, setCompleted] = entity.completed;
              const [start] = entity.start;
              const created = new Date(entity.created);
              const [, setUpdated] = entity.updated;
              const updated = createMemo(() => new Date(entity.updated[0]()));

              const [addingDependency, setAddingDependency] = createSignal(false);
              let dependencyInput!: HTMLInputElement;

              const EditableDateCell = ({
                value: [get, set],
              }: {
                value: Signal<string | undefined>;
              }): JSX.Element => (
                <td>
                  <div class="flex">
                    <EditableDate
                      class="grow"
                      value={get}
                      on:change={(e) => {
                        setUpdated(Date.now());
                        set(new Date(e.target.value).toISOString());
                      }}
                    />
                    <Show when={get()}>
                      <button on:click={() => set(undefined)}>x</button>
                    </Show>
                  </div>
                </td>
              );

              return (
                <Show
                  when={
                    (!hideBlocked() || !entity.blocked()) &&
                    (!hideCompleted() || !completed()) &&
                    (!hideFuture() || !start() || Date.parse(start()!) <= Date.now())
                  }
                >
                  <tr>
                    <td>
                      <EditableText
                        class="w-full"
                        value={name}
                        on:change={(e) => {
                          const v = e.target.value.trim();
                          if (v) {
                            setUpdated(Date.now());
                            setName(e.target.value.trim());
                          }
                        }}
                      />
                    </td>

                    <td>
                      <input
                        type="checkbox"
                        checked={completed()}
                        on:change={(e) => (setUpdated(Date.now()), setCompleted(e.target.checked))}
                      />
                    </td>

                    <EditableDateCell value={entity.start} />

                    <EditableDateCell value={entity.end} />

                    <td>
                      <div class="flex justify-between">
                        <div>
                          <For each={entityDependencies()}>
                            {([dependent, dependee], i) => (
                              <Show when={dependent === entity}>
                                <div class="border inline">
                                  {dependee.name[0]()}
                                  <button
                                    on:click={() =>
                                      setEntityDependencies((v) => v.toSpliced(i(), 1))
                                    }
                                  >
                                    x
                                  </button>
                                </div>
                              </Show>
                            )}
                          </For>
                        </div>

                        <Show
                          when={addingDependency()}
                          fallback={
                            <button
                              on:click={() => {
                                setAddingDependency(true);
                                dependencyInput.focus();
                              }}
                            >
                              +
                            </button>
                          }
                        >
                          <input
                            class="grow"
                            list="tasks"
                            ref={dependencyInput}
                            on:change={(e) => {
                              e.target.blur();
                              const dependee = entities().find(
                                ({ name: [name] }) => name() === e.target.value,
                              );
                              if (dependee) {
                                setEntityDependencies((v) => [...v, [entity, dependee]]);
                              }
                            }}
                            on:blur={() => setAddingDependency(false)}
                            on:keydown={(e) =>
                              (e.key === 'Escape' || e.key === 'Enter') && dependencyInput.blur()
                            }
                          />

                          <datalist id="tasks">
                            <For each={entities()}>
                              {(datalistEntity) => (
                                <Show
                                  when={
                                    // TODO: need to hide it if the entry's dependency chain includes `task`
                                    //       need to propagate dependencies up
                                    entity !== datalistEntity &&
                                    !entityDependencies().some(
                                      ([dependent, dependee]) =>
                                        dependent === entity && dependee === datalistEntity,
                                    )
                                  }
                                >
                                  <option>{datalistEntity.name[0]()}</option>
                                </Show>
                              )}
                            </For>
                          </datalist>
                        </Show>
                      </div>
                    </td>

                    <td title={created.toLocaleString()}>{created.toLocaleDateString()}</td>

                    <td title={updated().toLocaleString()}>{updated().toLocaleDateString()}</td>

                    <td class="text-right">
                      <button
                        on:click={() => {
                          setEntities((v) => v.toSpliced(i(), 1));
                          setEntityDependencies((dependencies) =>
                            dependencies.filter(
                              ([dependent, dependee]) =>
                                entity !== dependent && entity !== dependee,
                            ),
                          );
                        }}
                      >
                        Delete
                      </button>
                    </td>
                  </tr>
                </Show>
              );
            }}
          </For>
        </tbody>
      </table>
    </main>
  );
};
